In [1]:
import pandas as pd

C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\.libs\libopenblas.QVLO2T66WEPI7JZ63PS3HMOHFEY472BC.gfortran-win_amd64.dll
C:\Users\user\AppData\Local\Programs\Python\Python39\lib\site-packages\numpy\.libs\libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"

In [25]:
tt = pd.read_csv(r'C:\apps\Ubion-CorporateBankruptcyAnalysis\Code\SH\csv\대표이사변경00-20.csv', index_col=0) #kind에서 크롤링해온 대표이사변경 관련 데이터셋
df = pd.read_csv(r'..\..\..\Data\최종데이터셋\Finaldataset_ver3.csv', index_col=0)

In [26]:
df = pd.read_csv(r'..\..\..\Data\최종데이터셋\Finaldataset_ver3.csv', index_col=0)
t_11 = pd.read_csv(r'..\..\..\Data\데이터정리중\kindtextdata\0020공시11.csv', index_col=0)
t_56 = pd.read_csv(r'..\..\..\Data\데이터정리중\kindtextdata\0020공시56.csv', index_col=0)
t_65 = pd.read_csv(r'..\..\..\Data\데이터정리중\kindtextdata\0020공시65.csv', index_col=0)
t_67 = pd.read_csv(r'..\..\..\Data\데이터정리중\kindtextdata\0020공시67.csv', index_col=0)

In [27]:
t_56

,회사명,거래소코드,공시발생일,공시제목,text,link
0,신원종합개발,017000,2000-08-18 00:00,최대주주또는주요주주변경(신원종합개발(주) 최대주주 변경),신원종합개발(주) 최대주주 변경\r\n\r\n\r\n1. 최대주주 변경내용\r\n ...,https://kind.krx.co.kr/external/2000/08/18/M00...
1,에이치엘비,028300,2000-08-01 00:00,최대주주또는주요주주변경(국제정공(주) 최대주주 변경),국제정공(주) 최대주주 변경\r\n\r\n\r\n1. 최대주주 변경내용\r\n ...,https://kind.krx.co.kr/external/2000/08/01/M00...
2,에이치엘비,028300,2000-07-27 00:00,최대주주또는주요주주변경(국제정공(주) 최대주주 변경),국제정공(주) 최대주주 변경\r\n\r\n\r\n1. 최대주주 변경내용\r\n ...,https://kind.krx.co.kr/external/2000/07/27/M00...
3,휴먼이노텍,013630,2000-07-24 00:00,최대주주또는주요주주변경(대정기계공업(주) 최대주주 변경),대정기계공업(주) 최대주주 변경\r\n\r\n\r\n1. 최대주주 변경내용\r\n ...,https://kind.krx.co.kr/external/2000/07/24/M00...
4,써니트렌드,035500,2000-07-19 00:00,최대주주또는주요주주변경((주)디지탈임팩트 최대주주 변경 관련),(주)디지탈임팩트 최대주주 변경 관련\r\n\r\n\r\n당사가 기공시한 (주)새한...,https://kind.krx.co.kr/external/2000/07/19/M00...
...,...,...,...,...,...,...
4759,엔텔스,069410,2020-01-10 16:55,최대주주 변경을 수반하는 주식양수도 계약 체결,\r\n\r\n\r\n\r\n\r\n\r\n:: 71207_최대주주 변경을 수반하는...,https://kind.krx.co.kr/external/2020/01/10/000...
4760,부방,014470,2020-01-09 18:29,최대주주변경,\r\n\r\n\r\n\r\n\r\n\r\n:: 71209_최대주주 변경\r\n\r...,https://kind.krx.co.kr/external/2020/01/09/000...
4761,코디엠,224060,2020-01-08 16:13,[정정]최대주주 변경을 수반하는 주식 담보제공 계약 체결,\r\n\r\n\r\n\r\n\r\n\r\n:: 71993_최대주주 변경을 수반하는...,https://kind.krx.co.kr/external/2020/01/08/000...
4762,코썬바이오,204990,2020-01-07 17:42,[정정]최대주주 변경을 수반하는 주식 담보제공 계약 체결,\r\n\r\n\r\n\r\n\r\n\r\n:: 71993_최대주주 변경을 수반하는...,https://kind.krx.co.kr/external/2020/01/07/000...
4763,웰크론,065950,2020-01-02 17:01,[정정]최대주주 변경을 수반하는 주식 담보제공 계약 체결,\r\n\r\n\r\n\r\n\r\n\r\n:: 71993_최대주주 변경을 수반하는...,https://kind.krx.co.kr/external/2020/01/02/000...

In [28]:
t_11.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7528 entries, 0 to 7527
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   회사명     7528 non-null   object
 1   거래소코드   7528 non-null   object
 2   공시발생일   7528 non-null   object
 3   공시제목    7528 non-null   object
 4   text    7528 non-null   object
 5   link    7528 non-null   object
dtypes: object(6)
memory usage: 411.7+ KB

## 거래소코드 앞에 붙은 0 제거

In [29]:
# 거래소코드 앞에 붙은 0 제거

def elimination_0(data):
    for i in range(len(data)):
        if data['거래소코드'][i][:1] == '0':
            data['거래소코드'][i] = data['거래소코드'][i].lstrip("0")
    else : pass

In [30]:
elimination_0(t_11)
elimination_0(t_56)

## key 생성

In [31]:
t_11

,회사명,거래소코드,공시발생일,공시제목,text,link
0,엔케이바이오,19260,2000-12-29 18:25,대표이사변경,\n\n\n\n\n\n\n\n\n\n대표이사 변경 안내\n\n\n\n1.변경내용\n...,https://kind.krx.co.kr/external/2000/12/29/K00...
1,무한투자,34510,2000-12-20 16:20,대표이사변경,\n\n\n\n\n\n\n\n\n\n대표이사 변경 안내\n\n\n\n1.변경내용\n...,https://kind.krx.co.kr/external/2000/12/20/K00...
2,휴먼이노텍,13630,2000-12-18 15:14,대표이사변경,\n\n\n\n\n\n\n\n\n\n대표이사 변경 안내\n\n\n\n1.변경내용\n...,https://kind.krx.co.kr/external/2000/12/18/K00...
3,디에스티,33430,2000-12-18 14:02,대표이사변경,\n\n\n\n\n\n\n\n\n\n대표이사 변경 안내\n\n\n\n1.변경내용\n...,https://kind.krx.co.kr/external/2000/12/18/K00...
4,BNGT,32790,2000-12-15 16:54,대표이사변경,\n\n\n\n\n\n\n\n\n\n대표이사 변경 안내\n\n\n\n1.변경내용\n...,https://kind.krx.co.kr/external/2000/12/15/K00...
...,...,...,...,...,...,...
7523,서울전자통신,27040,2020-01-02 17:25,대표이사변경,\n\n\n\n\n\n:: 70656_대표이사 변경\n\n\n\n\n\n\n\n\n...,https://kind.krx.co.kr/external/2020/01/02/000...
7524,릭스솔루션,29480,2020-01-02 17:11,대표이사변경,\n\n\n\n\n\n:: 70656_대표이사 변경\n\n\n\n\n\n\n\n\n...,https://kind.krx.co.kr/external/2020/01/02/000...
7525,지니틱스,303030,2020-01-02 17:10,대표이사변경,\n\n\n\n\n\n:: 70656_대표이사 변경\n\n\n\n\n\n\n\n\n...,https://kind.krx.co.kr/external/2020/01/02/000...
7526,씨티씨바이오,60590,2020-01-02 14:11,대표이사변경,\n\n\n\n\n\n:: 70656_대표이사 변경\n\n\n\n\n\n\n\n\n...,https://kind.krx.co.kr/external/2020/01/02/000...
7527,수산아이앤티,50960,2020-01-02 13:53,대표이사변경,\n\n\n\n\n\n:: 70656_대표이사 변경\n\n\n\n\n\n\n\n\n...,https://kind.krx.co.kr/external/2020/01/02/000...

In [32]:
# key 생성

def key_maker(data):
    data['년'] = data['공시발생일'].str[0:4].astype(int)
    data['key'] = data['거래소코드'].astype(str) + (data['년']+1).astype(str)

In [33]:
key_maker(t_11)
key_maker(t_56)
key_maker(t_65)
key_maker(t_67)

In [34]:
t_67

,회사명,거래소코드,공시발생일,공시제목,text,link,년,key
0,씨엔씨엔터,38420,2005-12-23 19:53,횡령사고발생,\r\n\r\n\r\n\r\n\r\n\r\n\r\n횡령사고 발생\r\n\r\n\r\...,https://kind.krx.co.kr/external/2005/12/23/K00...,2005,384202006
1,넥슨지티,41140,2005-12-08 19:49,횡령사고발생,\r\n\r\n\r\n\r\n\r\n\r\n\r\n횡령사고 발생\r\n\r\n\r\...,https://kind.krx.co.kr/external/2005/12/08/K00...,2005,411402006
2,예일바이오텍,54250,2005-12-06 19:44,횡령사고발생,\r\n\r\n\r\n\r\n\r\n\r\n\r\n횡령사고 발생\r\n\r\n\r\...,https://kind.krx.co.kr/external/2005/12/06/K00...,2005,542502006
3,플러스프로핏,36660,2005-11-07 18:27,횡령사고발생,\r\n\r\n\r\n\r\n\r\n\r\n\r\n횡령사고 발생\r\n\r\n\r\...,https://kind.krx.co.kr/external/2005/11/07/K00...,2005,366602006
4,영진코퍼레이션,53330,2005-08-01 18:19,[정정]횡령사고발생,\r\n\r\n\r\n\r\n\r\n\r\n\r\n정 정 신 고 (보고)\r\n\r...,https://kind.krx.co.kr/external/2005/08/01/K00...,2005,533302006
...,...,...,...,...,...,...,...,...
825,시티랩스,139050,2018-02-12 16:54,횡령ㆍ배임 혐의 진행사항,\r\n\r\n\r\n\r\n\r\n\r\n:: 70057_횡령ㆍ배임 혐의 진행사항...,https://kind.krx.co.kr/external/2018/02/12/000...,2018,1390502019
826,이매진아시아,36260,2018-01-25 15:33,횡령ㆍ배임사실확인,\r\n\r\n\r\n\r\n\r\n\r\n:: 70009_횡령ㆍ배임 사실확인\r\...,https://kind.krx.co.kr/external/2018/01/25/000...,2018,362602019
827,엠피대산,65150,2018-01-24 15:37,횡령ㆍ배임사실확인,\r\n\r\n\r\n\r\n\r\n\r\n:: 70009_횡령ㆍ배임 사실확인\r\...,https://kind.krx.co.kr/external/2018/01/24/000...,2018,651502019
828,제이테크놀로지,35480,2018-01-05 18:43,횡령ㆍ배임혐의발생,\r\n\r\n\r\n\r\n\r\n\r\n:: 70008_횡령ㆍ배임 혐의발생\r\...,https://kind.krx.co.kr/external/2018/01/05/000...,2018,354802019
829,케이에스피,73010,2018-01-04 17:08,횡령ㆍ배임 혐의 진행사항,\r\n\r\n\r\n\r\n\r\n\r\n:: 70057_횡령ㆍ배임 혐의 진행사항...,https://kind.krx.co.kr/external/2018/01/04/000...,2018,730102019

## key 기준 value_counts df 생성

In [11]:
# 함수 만들고싶었는데 실패 ㅠ
# for df in [t_11, t_56, t_65, t_67]:
#     df['key'].value_counts()
#     subset_{}.format(df) = pd.DataFrame({'key' : df['key'].value_counts().index, '대표이사 변경' : df['key'].value_counts().values})

In [35]:
# 대표이사 변경
t_11['key'].value_counts()
subset_11 = pd.DataFrame({'key' : t_11['key'].value_counts().index, '대표이사 변경' : t_11['key'].value_counts().values})
subset_11

            key  대표이사 변경
0     540102008        9
1     531102017        9
2     787002009        7
3     760902009        7
4     386902010        7
...         ...      ...
5278  110402010        1
5279  396702010        1
5280  280802010        1
5281  746002010        1
5282  605902021        1

[5283 rows x 2 columns]

In [36]:
# 최대주주 변경
t_56['key'].value_counts()
subset_56 = pd.DataFrame({'key' : t_56['key'].value_counts().index, '최대주주 변경' : t_56['key'].value_counts().values})
subset_56

             key  최대주주 변경
0      364202020       13
1     2148702018       11
2     2263502018       10
3      522102010       10
4      144202009       10
...          ...      ...
2762   741402010        1
2763   859902010        1
2764   787002010        1
2765   237902010        1
2766  2049902021        1

[2767 rows x 2 columns]

In [37]:
# 최대주주 변경
t_65['key'].value_counts()
subset_65 = pd.DataFrame({'key' : t_65['key'].value_counts().index, '회계처리위반' : t_65['key'].value_counts().values})
subset_65

           key  회계처리위반
0    208602002       3
1    426002004       3
2    350802003       3
3    195402005       3
4    396102001       2
..         ...     ...
342  668502006       1
343  667902006       1
344  438902006       1
345  463102006       1
346  664302019       1

[347 rows x 2 columns]

In [38]:
# 횡령배임
t_67['key'].value_counts()
subset_67 = pd.DataFrame({'key' : t_67['key'].value_counts().index, '횡령배임' : t_67['key'].value_counts().values})
subset_67

            key  횡령배임
0     659402020    20
1     582202021    13
2     435902020    12
3     529702011    11
4    9500302012     8
..          ...   ...
426   416302011     1
427   410302011     1
428   372402011     1
429   504702011     1
430   354802019     1

[431 rows x 2 columns]

## 생성한 subset을 df와 merge
subset_11<br>
subset_56<br>
subset_65<br>
subset_67<br>

In [39]:
#df key int라서 다른 subset과 동일하게 str로 변환해줌
df['key']=df['key'].astype(str)

In [17]:
# subset_11<br>
# subset_56<br>
# subset_65<br>
# subset_67<br>
#df.merge(subset, how='outer', on='key')

In [40]:
subset_merge = df.merge(subset_11, how='outer', on='key')
subset_merge = subset_merge.merge(subset_56, how='outer', on='key')
subset_merge = subset_merge.merge(subset_65, how='outer', on='key')
subset_merge = subset_merge.merge(subset_67, how='outer', on='key')

In [41]:
subset_merge

,회사명,거래소코드,회계년도,소속코드,상장폐지일,감사의견코드,자기자본배당률,금융비용 대 부채비율,자기자본배율,유동부채비율,...,link,TS,폐지사유,폐지사유요약,정기공시제목,수시공시제목,대표이사 변경,최대주주 변경,회계처리위반,횡령배임
0,(주)CMG제약,58820.0,2000/12,5.0,0,UQ,0.0,0.019074,179.37,131.99,...,0,0,0,0,0,0,NaN,NaN,NaN,NaN
1,(주)CMG제약,58820.0,2001/12,5.0,0,UQ,0.0,0.023517,179.37,131.99,...,0,0,0,0,0,0,NaN,NaN,NaN,NaN
2,(주)CMG제약,58820.0,2002/12,5.0,0,UQ,0.0,0.043081,133.37,132.37,...,0,0,0,0,0,0,1.0,NaN,NaN,NaN
3,(주)CMG제약,58820.0,2003/12,5.0,0,UQ,0.0,0.058531,131.30,71.46,...,0,0,0,0,0,0,1.0,NaN,NaN,NaN
4,(주)CMG제약,58820.0,2004/12,5.0,0,UQ,0.0,0.047346,52.25,101.56,...,0,0,0,0,0,0,1.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27874,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
27875,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
27876,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
27877,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
27878,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0

In [42]:
subset_merge.isnull().sum().sort_values()

key                0
회사명              726
수시공시제목           726
정기공시제목           726
폐지사유요약           726
폐지사유             726
TS               726
link             726
text             726
공시발생일            726
부도               726
년                726
총자산회전율           726
누적수익성비율          726
총자산영업이익률         726
감사의견코드           726
총자본투자효율          726
유동자산회전률          726
매입채무회전률          726
유동부채비율           726
자기자본배율           726
금융비용 대 부채비율      726
자기자본배당률          726
순운전자본비율          726
상장폐지일            726
소속코드             726
회계년도             726
거래소코드            726
대표이사 변경        22431
최대주주 변경        24966
횡령배임           27372
회계처리위반         27512
dtype: int64

In [43]:
subset_merge['회계처리위반'] = subset_merge['회계처리위반'].fillna(0)
subset_merge['횡령배임'] = subset_merge['횡령배임'].fillna(0)
subset_merge['최대주주 변경'] = subset_merge['최대주주 변경'].fillna(0)
subset_merge['대표이사 변경'] = subset_merge['대표이사 변경'].fillna(0)

In [44]:
subset_merge.isnull().sum().sort_values()

횡령배임             0
최대주주 변경          0
대표이사 변경          0
key              0
회계처리위반           0
수시공시제목         726
정기공시제목         726
폐지사유요약         726
폐지사유           726
TS             726
link           726
text           726
공시발생일          726
부도             726
년              726
총자산회전율         726
회사명            726
순운전자본비율        726
총자본투자효율        726
유동자산회전률        726
매입채무회전률        726
유동부채비율         726
자기자본배율         726
금융비용 대 부채비율    726
자기자본배당률        726
감사의견코드         726
상장폐지일          726
소속코드           726
회계년도           726
거래소코드          726
누적수익성비율        726
총자산영업이익률       726
dtype: int64

In [45]:
subset_merge

,회사명,거래소코드,회계년도,소속코드,상장폐지일,감사의견코드,자기자본배당률,금융비용 대 부채비율,자기자본배율,유동부채비율,...,link,TS,폐지사유,폐지사유요약,정기공시제목,수시공시제목,대표이사 변경,최대주주 변경,회계처리위반,횡령배임
0,(주)CMG제약,58820.0,2000/12,5.0,0,UQ,0.0,0.019074,179.37,131.99,...,0,0,0,0,0,0,0.0,0.0,0.0,0.0
1,(주)CMG제약,58820.0,2001/12,5.0,0,UQ,0.0,0.023517,179.37,131.99,...,0,0,0,0,0,0,0.0,0.0,0.0,0.0
2,(주)CMG제약,58820.0,2002/12,5.0,0,UQ,0.0,0.043081,133.37,132.37,...,0,0,0,0,0,0,1.0,0.0,0.0,0.0
3,(주)CMG제약,58820.0,2003/12,5.0,0,UQ,0.0,0.058531,131.30,71.46,...,0,0,0,0,0,0,1.0,0.0,0.0,0.0
4,(주)CMG제약,58820.0,2004/12,5.0,0,UQ,0.0,0.047346,52.25,101.56,...,0,0,0,0,0,0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27874,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0
27875,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0
27876,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0
27877,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0
27878,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,1.0

In [46]:
subset_merge = subset_merge.dropna()

In [47]:
subset_merge

,회사명,거래소코드,회계년도,소속코드,상장폐지일,감사의견코드,자기자본배당률,금융비용 대 부채비율,자기자본배율,유동부채비율,...,link,TS,폐지사유,폐지사유요약,정기공시제목,수시공시제목,대표이사 변경,최대주주 변경,회계처리위반,횡령배임
0,(주)CMG제약,58820.0,2000/12,5.0,0,UQ,0.00,0.019074,179.37,131.99,...,0,0,0,0,0,0,0.0,0.0,0.0,0.0
1,(주)CMG제약,58820.0,2001/12,5.0,0,UQ,0.00,0.023517,179.37,131.99,...,0,0,0,0,0,0,0.0,0.0,0.0,0.0
2,(주)CMG제약,58820.0,2002/12,5.0,0,UQ,0.00,0.043081,133.37,132.37,...,0,0,0,0,0,0,1.0,0.0,0.0,0.0
3,(주)CMG제약,58820.0,2003/12,5.0,0,UQ,0.00,0.058531,131.30,71.46,...,0,0,0,0,0,0,1.0,0.0,0.0,0.0
4,(주)CMG제약,58820.0,2004/12,5.0,0,UQ,0.00,0.047346,52.25,101.56,...,0,0,0,0,0,0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27148,흥구석유(주),24060.0,2016/12,5.0,0,UQ,2.10,0.012651,4611.84,5.19,...,0,0,0,0,0,0,0.0,0.0,0.0,0.0
27149,흥구석유(주),24060.0,2017/12,5.0,0,UQ,2.08,0.012502,4650.29,12.83,...,0,0,0,0,0,0,0.0,0.0,0.0,0.0
27150,흥구석유(주),24060.0,2018/12,5.0,0,UQ,2.48,0.018056,4696.15,5.40,...,0,0,0,0,0,0,0.0,0.0,0.0,0.0
27151,흥구석유(주),24060.0,2019/12,5.0,0,UQ,2.83,0.000300,5133.42,6.05,...,0,0,0,0,0,0,0.0,0.0,0.0,0.0
27152,흥구석유(주),24060.0,2020/12,5.0,0,UQ,2.74,0.000000,5306.68,3.14,...,0,0,0,0,0,0,0.0,0.0,0.0,0.0

In [53]:
subset_merge[subset_merge['회사명']=='(주)경윤하이드로에너지']

,회사명,거래소코드,회계년도,소속코드,상장폐지일,감사의견코드,자기자본배당률,금융비용 대 부채비율,자기자본배율,유동부채비율,...,link,TS,폐지사유,폐지사유요약,정기공시제목,수시공시제목,대표이사 변경,최대주주 변경,회계처리위반,횡령배임
109,(주)경윤하이드로에너지,19120.0,2000/12,4.0,2011/04/06,UQ,3.49,0.064542,500.94,54.92,...,0,0,0,0,0,0,0.0,0.0,1.0,0.0
110,(주)경윤하이드로에너지,19120.0,2001/12,4.0,2011/04/06,UQ,3.07,0.041816,548.78,51.69,...,0,0,0,0,0,0,2.0,0.0,0.0,0.0
111,(주)경윤하이드로에너지,19120.0,2002/12,4.0,2011/04/06,UQ,2.70,0.025819,591.40,44.84,...,0,0,0,0,0,0,0.0,0.0,0.0,0.0
112,(주)경윤하이드로에너지,19120.0,2003/12,4.0,2011/04/06,UQ,2.16,0.014166,716.01,47.65,...,0,0,0,0,0,0,0.0,0.0,0.0,0.0
113,(주)경윤하이드로에너지,19120.0,2004/12,4.0,2011/04/06,UQ,1.65,0.018528,658.53,57.65,...,0,0,0,0,0,0,0.0,0.0,0.0,0.0
114,(주)경윤하이드로에너지,19120.0,2005/12,4.0,2011/04/06,UQ,1.85,0.038683,619.61,62.01,...,0,0,0,0,0,0,0.0,0.0,0.0,0.0
115,(주)경윤하이드로에너지,19120.0,2006/12,4.0,2011/04/06,UQ,0.00,0.042356,483.44,90.26,...,0,0,0,0,0,0,0.0,0.0,0.0,0.0
116,(주)경윤하이드로에너지,19120.0,2007/12,4.0,2011/04/06,UQ,0.00,0.046518,396.15,114.41,...,0,0,0,0,0,0,1.0,0.0,0.0,0.0
117,(주)경윤하이드로에너지,19120.0,2008/12,4.0,2011/04/06,UQ,0.00,0.064591,68.32,200.40,...,0,0,0,0,0,0,1.0,2.0,0.0,0.0
118,(주)경윤하이드로에너지,19120.0,2009/12,4.0,2011/04/06,UQ,0.00,0.045389,72.99,40.06,...,0,0,0,0,0,0,5.0,0.0,0.0,0.0
119,(주)경윤하이드로에너지,19120.0,2010/12,4.0,2011/04/06,UQ,0.00,0.072789,17.52,54.90,...,https://kind.krx.co.kr/external/2011/03/24/000...,True,5.상장폐지사유\n기업의 계속성 및 경영의 투명성 등을 종합적으로 고려하여 상장폐지...,기업의 계속성 및 경영의 투명성 등을 종합적으로 고려하여 상장폐지 기준에 해당한다고 결정,0,상장폐지,0.0,1.0,0.0,0.0

In [51]:
subset_merge[subset_merge['대표이사 변경']==5]

,회사명,거래소코드,회계년도,소속코드,상장폐지일,감사의견코드,자기자본배당률,금융비용 대 부채비율,자기자본배율,유동부채비율,...,link,TS,폐지사유,폐지사유요약,정기공시제목,수시공시제목,대표이사 변경,최대주주 변경,회계처리위반,횡령배임
118,(주)경윤하이드로에너지,19120.0,2009/12,4.0,2011/04/06,UQ,0.0,0.045389,72.99,40.06,...,0,0,0,0,0,0,5.0,0.0,0.0,0.0
414,(주)글로포스트,37830.0,2004/12,4.0,2010/02/09,UQ,0.0,0.043339,39.02,19.76,...,0,0,0,0,0,0,5.0,0.0,0.0,0.0
679,(주)네오리소스,58550.0,2005/12,4.0,2009/09/15,QU,0.0,0.091817,101.86,355.51,...,0,0,0,0,0,0,5.0,4.0,0.0,0.0
893,(주)넥스지,81970.0,2017/12,4.0,2018/10/11,DS,0.0,0.001146,1233.64,8.62,...,https://kind.krx.co.kr/external/2018/09/27/000...,True,5.상장폐지사유\n감사의견거절(감사범위제한)\n\n\n,감사의견거절(감사범위제한),0,상장폐지,5.0,9.0,0.0,0.0
1863,(주)도움,78610.0,2008/12,4.0,2009/04/11,DU,0.0,0.061341,0.00,0.00,...,https://kind.krx.co.kr/external/2009/04/01/000...,True,5.상장폐지사유\n자본전액잠식\n\n\n,자본전액잠식,0,상장폐지,5.0,1.0,0.0,2.0
3698,(주)모빌탑,85680.0,2008/12,4.0,2009/11/25,UQ,0.0,0.082290,166.59,20.13,...,https://kind.krx.co.kr/external/2009/11/12/000...,True,"5.상장폐지사유\n기업의 계속성, 경영의 투명성 또는 기타 코스닥시장의 건전성 등을...","기업의 계속성, 경영의 투명성 또는 기타 코스닥시장의 건전성 등을 종합적으로 고려하...",0,상장폐지,5.0,3.0,0.0,7.0
4771,(주)사이버패스,63280.0,2008/12,4.0,2009/07/08,UQ,0.0,0.122200,60.31,553.99,...,https://kind.krx.co.kr/external/2009/06/25/000...,True,"5.상장폐지사유\n기업의 계속성, 경영의 투명성 또는 기타 코스닥시장의 건전성 등을...","기업의 계속성, 경영의 투명성 또는 기타 코스닥시장의 건전성 등을 종합적으로 고려하...",0,상장폐지,5.0,1.0,0.0,1.0
6592,(주)신지소프트,78700.0,2007/12,4.0,2010/02/27,UQ,0.0,0.092491,0.00,0.00,...,0,0,0,0,0,0,5.0,1.0,0.0,1.0
8401,(주)야호커뮤니케이션,59720.0,2008/12,4.0,2009/05/27,DS,0.0,0.022414,32.68,487.62,...,https://kind.krx.co.kr/external/2009/05/14/000...,True,5.상장폐지사유\n감사의견거절(감사범위제한)\n\n\n,감사의견거절(감사범위제한),0,상장폐지(감사의견거절),5.0,2.0,0.0,1.0
8498,(주)에듀패스,31950.0,2010/12,4.0,2011/06/09,UQ,0.0,0.285087,66.95,64.18,...,https://kind.krx.co.kr/external/2011/05/26/000...,True,"5.상장폐지사유\n기업의 계속성, 경영의 투명성 또는 기타 코스닥시장의 건전성 등을...","기업의 계속성, 경영의 투명성 또는 기타 코스닥시장의 건전성 등을 종합적으로 고려하...",0,상장폐지,5.0,1.0,0.0,1.0
8569,(주)에스브이에이치,46240.0,2009/12,4.0,2011/02/12,UQ,0.0,0.243640,58.03,239.78,...,0,0,0,0,0,0,5.0,3.0,0.0,0.0
9200,(주)에이디모터스,38120.0,2009/12,4.0,2013/01/30,UQ,0.0,0.371564,917.06,7.30,...,0,0,0,0,0,0,5.0,1.0,0.0,0.0
9592,(주)에이프로테크놀로지,45470.0,2008/12,4.0,2012/04/24,UQ,0.0,0.089613,100.05,161.52,...,0,0,0,0,내부결산시점 관리종목 지정 또는 상장폐지 사유 발생,0,5.0,0.0,0.0,0.0
9611,(주)에임하이글로벌,43580.0,2016/12,4.0,2018/08/10,UQ,0.0,0.044638,203.98,36.62,...,0,0,0,0,0,0,5.0,2.0,0.0,0.0
9663,(주)에코페트로시스템,42870.0,2004/12,4.0,2011/10/06,UQ,0.0,0.078739,0.00,0.00,...,0,0,0,0,0,0,5.0,0.0,0.0,0.0
9900,(주)엑큐리스,48460.0,2010/12,4.0,2012/11/16,UQ,0.0,0.053235,78.35,137.76,...,0,0,0,0,0,0,5.0,3.0,0.0,0.0
10209,(주)엘앤씨피,15390.0,2008/12,4.0,2012/04/13,QU,0.0,0.102883,0.00,0.00,...,0,0,0,0,파산신청,0,5.0,1.0,0.0,0.0
11684,(주)위너지스,26260.0,2017/12,4.0,2018/10/11,DS,0.0,0.266735,66.80,22.71,...,https://kind.krx.co.kr/external/2018/09/27/000...,True,5.상장폐지사유\n감사의견거절(감사범위 제한)\n\n\n,감사의견거절(감사범위 제한),0,상장폐지,5.0,2.0,0.0,0.0
12177,(주)유아이에너지,50050.0,2005/12,4.0,2012/09/26,UQ,0.0,0.058578,87.94,102.87,...,https://kind.krx.co.kr/external/2006/04/03/K00...,True,5.상장폐지사유\n감사범위제한으로 인한 의견거절(상장폐지사유 발생일 : 2006년 ...,감사범위제한으로 인한 의견거절(상장폐지사유 발생일 : 2006년 03월 30일),0,상장폐지,5.0,3.0,2.0,0.0
12517,(주)이롬텍,45400.0,2008/10,4.0,2010/02/11,QU,0.0,0.081997,68.31,25.93,...,0,0,0,0,0,0,5.0,2.0,0.0,5.0
14277,(주)지디코프,36610.0,2008/12,4.0,2009/06/17,UQ,0.0,0.155943,0.00,0.00,...,https://kind.krx.co.kr/external/2009/06/04/000...,True,"5.상장폐지사유\n기업의 계속성, 경영의 투명성 또는 기타 코스닥시장의 건전성 등을...","기업의 계속성, 경영의 투명성 또는 기타 코스닥시장의 건전성 등을 종합적으로 고려하...",0,상장폐지,5.0,3.0,0.0,3.0
14464,(주)지이엔에프,38920.0,2005/12,4.0,2009/05/29,UQ,0.0,0.000000,757.90,23.60,...,0,0,0,0,0,0,5.0,0.0,0.0,0.0
14678,(주)청람디지탈,35270.0,2006/12,4.0,2008/04/23,UQ,0.0,0.035443,36.25,255.61,...,0,0,0,0,0,0,5.0,3.0,0.0,0.0
15944,(주)코어비트,56850.0,2008/12,4.0,2010/03/09,UQ,0.0,0.000516,608.17,10.76,...,0,0,0,0,0,0,5.0,2.0,0.0,1.0
17558,(주)포네이처,45290.0,2009/12,4.0,2010/04/23,DU,0.0,0.011755,0.00,0.00,...,https://kind.krx.co.kr/external/2010/04/12/000...,True,5.상장폐지사유\n사업보고서 법정제출기한 익일부터 10일이내 미제출\n\n\n,사업보고서 법정제출기한 익일부터 10일이내 미제출,0,상장폐지,5.0,1.0,0.0,0.0
17559,(주)포네이처,45290.0,2009/12,4.0,2010/04/23,DU,0.0,0.011755,0.00,0.00,...,https://kind.krx.co.kr/external/2010/04/01/000...,True,2. 정정관련 공시서류 제출일 : \n2010-03-31\n\n\n,2010-03-31,0,[정정]상장폐지,5.0,1.0,0.0,0.0
17560,(주)포네이처,45290.0,2009/12,4.0,2010/04/23,DU,0.0,0.011755,0.00,0.00,...,https://kind.krx.co.kr/external/2010/03/31/002...,True,5.상장폐지사유\n자본전액잠식\n\n\n,자본전액잠식,0,상장폐지,5.0,1.0,0.0,0.0
17775,(주)폴켐,33190.0,2008/12,4.0,2010/04/23,UQ,0.0,0.077143,26.88,447.31,...,0,0,0,0,0,0,5.0,4.0,0.0,0.0
17907,(주)프로비타,14420.0,2008/12,4.0,2009/11/06,UQ,0.0,0.018056,342.73,56.95,...,https://kind.krx.co.kr/external/2009/10/21/000...,True,5.상장폐지사유\n주된 영업의 정지에 의한 상장폐지기준 해당\n\n\n,주된 영업의 정지에 의한 상장폐지기준 해당,0,상장폐지,5.0,10.0,0.0,1.0
20155,넥슨지티(주),41140.0,2004/12,5.0,0,UQ,0.0,0.059761,0.00,0.00,...,0,0,0,0,0,0,5.0,1.0,0.0,0.0
20949,동화기업(주),25900.0,2010/12,5.0,0,UQ,0.0,0.044279,2332.03,23.29,...,0,0,0,0,해산사유발생(자회사의 주요경영사항),0,5.0,0.0,0.0,0.0
20950,동화기업(주),25900.0,2010/12,5.0,0,UQ,0.0,0.044279,2332.03,23.29,...,0,0,0,0,해산사유발생(자회사의 주요경영사항),0,5.0,0.0,0.0,0.0
22203,세종텔레콤(주),36630.0,2001/12,5.0,0,UQ,0.0,0.012256,168.53,33.23,...,0,0,0,0,0,0,5.0,0.0,0.0,0.0
22298,시큐리티코리아(주),66330.0,2007/12,4.0,2008/04/12,DS,0.0,0.134667,4.56,3074.44,...,https://kind.krx.co.kr/external/2008/04/01/K00...,True,5.상장폐지사유\n2연속 자본잠식률 50%이상 및 자기자본 10억원 미만\n\n\n,2연속 자본잠식률 50%이상 및 자기자본 10억원 미만,0,상장폐지,5.0,0.0,0.0,2.0
22537,씨앤씨엔터프라이즈(주),38420.0,2005/12,4.0,2007/08/29,QU,0.0,0.080645,0.00,0.00,...,0,0,0,0,0,0,5.0,2.0,0.0,1.0
22682,아래스(주),50320.0,2017/12,6.0,0,UQ,0.0,0.000000,182.99,134.30,...,0,0,0,0,0,0,5.0,0.0,0.0,8.0
23483,에이치엘비(주),28300.0,2003/12,5.0,0,QG,0.0,0.096125,97.87,267.86,...,0,0,0,0,회사정리절차종결신청,0,5.0,0.0,0.0,0.0
26144,평안물산(주),37240.0,2008/12,4.0,2012/06/01,UQ,0.0,0.058936,386.31,36.08,...,0,0,0,0,내부결산시점 관리종목 지정 또는 상장폐지 사유 발생,0,5.0,0.0,0.0,3.0

In [48]:
subset_merge[subset_merge['거래소코드']==10670]

,회사명,거래소코드,회계년도,소속코드,상장폐지일,감사의견코드,자기자본배당률,금융비용 대 부채비율,자기자본배율,유동부채비율,...,link,TS,폐지사유,폐지사유요약,정기공시제목,수시공시제목,대표이사 변경,최대주주 변경,회계처리위반,횡령배임
562,(주)나노트로닉스,10670.0,2000/12,4.0,2014/04/11,UQ,0.0,0.092129,67.40,112.91,...,0,0,0,0,파산신청,0,0.0,0.0,1.0,0.0
563,(주)나노트로닉스,10670.0,2001/12,4.0,2014/04/11,UQ,0.0,0.968675,58.07,5.45,...,0,0,0,0,파산신청,0,7.0,0.0,0.0,0.0
564,(주)나노트로닉스,10670.0,2002/12,4.0,2014/04/11,UQ,0.0,0.000000,55.37,1.96,...,0,0,0,0,파산신청,0,0.0,0.0,0.0,0.0
565,(주)나노트로닉스,10670.0,2003/12,4.0,2014/04/11,UQ,0.0,0.000000,182.50,1.84,...,0,0,0,0,파산신청,0,0.0,0.0,0.0,0.0
566,(주)나노트로닉스,10670.0,2004/12,4.0,2014/04/11,UQ,0.0,0.015957,155.98,1.70,...,0,0,0,0,파산신청,0,0.0,0.0,0.0,0.0
567,(주)나노트로닉스,10670.0,2005/12,4.0,2014/04/11,UQ,0.0,0.020701,121.87,6.52,...,0,0,0,0,파산신청,0,0.0,0.0,0.0,0.0
568,(주)나노트로닉스,10670.0,2006/12,4.0,2014/04/11,UQ,0.0,0.004635,241.65,13.03,...,0,0,0,0,파산신청,0,1.0,2.0,0.0,0.0
569,(주)나노트로닉스,10670.0,2007/12,4.0,2014/04/11,UQ,0.0,0.112281,325.69,9.48,...,0,0,0,0,파산신청,0,0.0,0.0,0.0,0.0
570,(주)나노트로닉스,10670.0,2008/12,4.0,2014/04/11,UQ,0.0,0.000000,431.81,5.54,...,0,0,0,0,파산신청,0,0.0,0.0,0.0,0.0
571,(주)나노트로닉스,10670.0,2009/12,4.0,2014/04/11,UQ,0.0,0.042964,463.95,13.57,...,0,0,0,0,파산신청,0,0.0,0.0,0.0,0.0
572,(주)나노트로닉스,10670.0,2010/12,4.0,2014/04/11,UQ,0.0,0.076568,347.74,18.17,...,0,0,0,0,파산신청,0,0.0,0.0,0.0,0.0
573,(주)나노트로닉스,10670.0,2011/12,4.0,2014/04/11,UQ,0.0,0.070720,389.24,101.34,...,0,0,0,0,파산신청,0,0.0,0.0,0.0,0.0
574,(주)나노트로닉스,10670.0,2012/12,4.0,2014/04/11,UQ,0.0,0.080710,369.83,102.12,...,0,0,0,0,파산신청,0,0.0,0.0,0.0,0.0

In [54]:
subset_merge.to_csv('Finaldataset_ver4.csv')

In [49]:
subset_merge['대표이사 변경'].value_counts()

0.0    22266
1.0     3500
2.0      934
3.0      278
4.0      117
5.0       38
6.0       11
7.0        7
9.0        2
Name: 대표이사 변경, dtype: int64

In [50]:
subset_merge.isnull().sum()

회사명            0
거래소코드          0
회계년도           0
소속코드           0
상장폐지일          0
감사의견코드         0
자기자본배당률        0
금융비용 대 부채비율    0
자기자본배율         0
유동부채비율         0
매입채무회전률        0
유동자산회전률        0
총자본투자효율        0
순운전자본비율        0
누적수익성비율        0
총자산영업이익률       0
총자산회전율         0
년              0
key            0
부도             0
공시발생일          0
text           0
link           0
TS             0
폐지사유           0
폐지사유요약         0
정기공시제목         0
수시공시제목         0
대표이사 변경        0
최대주주 변경        0
회계처리위반         0
횡령배임           0
dtype: int64