In [38]:
import pandas as pd

In [39]:
dataset = pd.read_csv(r'C:\Users\JH\Desktop\Final\Ubion-CorporateBankruptcyAnalysis\Data\최종데이터셋\finaldataset_ver7.7.csv')

# **회계년도가 짧은 회사 모음**

In [40]:
cpyname = dataset.loc[dataset['부도'] == 1]['회사명'].unique()

shtcpy = [] # 회계기간이 짧은 회사 list
shtidx = [] # 회계기간이 짧은 회사의 idx
for i in cpyname:
    if len(dataset.loc[dataset['회사명'] == i]) < 5:
        shtcpy.append(i)
for i in shtcpy:
    shtidx.append(dataset.loc[dataset['회사명'] == i].index[-1])

shtidx

[871,
 984,
 1163,
 1324,
 1944,
 2584,
 3029,
 3496,
 3527,
 3980,
 4104,
 4134,
 5918,
 6075,
 6199,
 6329,
 6387,
 6497,
 6543,
 6633,
 6802,
 6830,
 7570,
 7731,
 8279,
 8799,
 9940,
 10802,
 11085,
 11378,
 11450,
 11710,
 11719,
 12321,
 14548,
 15297,
 15425,
 16106,
 16161,
 16235,
 16312,
 16478,
 17587,
 18019,
 18038,
 18488,
 18898,
 18943,
 18977,
 19092,
 19949,
 20355,
 20736,
 20887,
 21579,
 21609,
 21828,
 21876,
 21955,
 22193,
 22899,
 23434,
 23557,
 25393,
 25673,
 26279]

# **N년 전 부도 데이터 만들기**

In [41]:
num = 1

In [46]:
cpyidx = []
bfidx = []
for idx_ in dataset.loc[dataset['부도'] == 1].index:
    cpyidx.append(idx_)

for name in shtidx:
    try:
        cpyidx.remove(name)
    except ValueError:
        print(name)
        

for idx_ in cpyidx:
    bfidx.append(idx_ - num)

In [47]:
dataset.at[bfidx, '부도'] = 1
dataset = dataset.drop(index = cpyidx)

In [44]:
dataset['Year'] = dataset['key'].astype(str).str[-4:]
dataset = dataset.drop('key', axis=1)

In [48]:
dataset.loc[dataset['회사명'] == '(주)경윤하이드로에너지'][4:]

,회사명,경영자산비율,부채구성비율,유형자산회전율,자기자본배율,유동비율,총자본순이익률,자기자본영업이익률,경영자본영업이익률,매출액증가율,...,대표이사_변경,최대주주_변경,횡령배임,출자목적_투자,출자목적_경영권,출자목적_영업이익,신종채권자금조달방식_사모,신종채권자금조달방식_공모,부도,Year
113,(주)경윤하이드로에너지,64.588304,43.210858,5.88,658.53,150.71,3.49,0.45,0.41,-5.60,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2005
114,(주)경윤하이드로에너지,64.526361,42.030492,5.44,619.61,140.16,-4.77,-15.26,-13.40,-17.30,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2006
115,(주)경윤하이드로에너지,60.200884,50.210258,6.58,483.44,107.25,-8.62,-21.57,-18.44,6.31,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2007
116,(주)경윤하이드로에너지,47.529969,54.911943,6.89,396.15,70.34,-7.51,-23.41,-20.28,-11.26,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2008
117,(주)경윤하이드로에너지,30.111260,67.801626,5.82,68.32,20.74,-22.76,-9.78,-10.67,-17.22,...,1.0,2.0,0.0,0.0,0.0,0.0,1.0,2.0,1.0,2009

In [23]:
dataset.to_csv(r'C:\Users\JH\Desktop\Final\Ubion-CorporateBankruptcyAnalysis\Code\JH\data\ver3\year4.csv', index=False)

# **데이터 클리닝**

In [17]:
dataset.loc[dataset['회사명'] == dataset.at[20741, '회사명']]

,회사명,거래소코드,회계년도,유동비율,당좌비율,유동부채비율,비유동비율,순운전자본비율,부채비율,차입금의존도,...,기타,외국인_주식분포비율,종가,종가변동률,년,key,부도,신종채권_운영,신종채권_시설,신종채권_기타
20738,디와이엘엔제이(주),207230.0,2012/12,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,2012.0,2.072302e+09,0.0,0.0,0.0,0.0
20739,디와이엘엔제이(주),207230.0,2013/12,101.48,62.71,373.84,258.15,0.87,537.51,47.73,...,0.0,0.0,0.0,0.0,2013.0,2.072302e+09,1.0,0.0,0.0,0.0
20740,디와이엘엔제이(주),207230.0,2014/12,114.98,60.94,335.71,235.37,8.10,521.38,57.55,...,2.0,0.0,0.0,0.0,2014.0,2.072302e+09,0.0,0.0,0.0,0.0
20741,디와이엘엔제이(주),207230.0,2015/12,109.56,42.75,494.26,301.46,5.61,742.98,60.56,...,0.0,0.0,0.0,0.0,2015.0,2.072302e+09,0.0,0.0,0.0,0.0

In [18]:
dataset.at[20739,'부도'] = 0
dataset.at[20741,'부도'] = 1