# **라이브러리**

In [1]:
import pandas as pd

In [2]:
bankrupt = pd.read_csv(r'C:\Users\JH\Desktop\Final\CBA\Data\kind_bankrupt.csv', index_col ='Unnamed: 0')
train_full = pd.read_csv(r'C:\Users\JH\Desktop\Final\CBA\Data\코드_재무변수.csv', encoding='euc-kr')
train = pd.read_csv(r'C:\Users\JH\Desktop\Final\CBA\Data\코드_재무변수.csv', encoding='euc-kr', usecols = ['회사명','거래소코드','회계년도','소속코드','상장폐지일'])

In [3]:
bankrupt.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 394 entries, 0 to 99
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   번호      394 non-null    int64
 1   시간      394 non-null    object
 2   회사명     394 non-null    object
 3   종목코드    394 non-null    int64
 4   공시제목    394 non-null    object
 5   제출인     386 non-null    object
dtypes: int64(2), object(4)
memory usage: 21.5+ KB

# **결측치 확인**

In [4]:
for i in range(267): 
    print(train_full.columns[i], train_full[train_full.columns[i]].isnull().sum())

회사명 0
거래소코드 0
회계년도 0
소속코드 0
상장폐지일 21826
감사의견코드 513
자산총계(요약) 333
유동자산(요약) 333
당좌자산(요약) 333
현금 및 현금성자산(요약) 333
단기투자자산(요약) 333
단기예금(요약) 333
단기매매증권(요약) 333
단기대여금(요약) 333
기타단기투자자산(요약) 333
매출채권(요약) 333
*할인어음 또는 배서어음(요약) 333
기타당좌자산(요약) 333
재고자산(요약) 333
상품(요약) 333
제품(요약) 333
반제품(요약) 333
재공품(요약) 333
원재료(요약) 333
기타재고자산(요약) 333
임대주택자산(요약) 333
비유동자산(요약) 333
투자자산(요약) 333
*장기금융상품(요약) 333
*투자유가증권(장기투자증권)(요약) 333
유형자산(요약) 333
토지 333
건설중인자산 333
건물 333
기계장치 333
차량운반구 333
렌탈자산 333
설비자산 333
무형자산(요약) 333
기타비유동자산(요약) 333
이연자산(요약) 333
부채총계(요약) 333
유동부채(요약) 333
매입채무(요약) 333
단기차입금(요약) 333
유동성장기부채(요약) 333
기타유동부채(요약) 333
비유동부채(요약) 333
사채(요약) 333
장기차입금(요약) 333
제충당금(요약) 333
기타비유동부채(요약) 333
이연부채(요약) 333
자본총계(요약) 333
자본금(요약) 333
자본잉여금(요약) 333
자본조정(요약) 333
기타포괄손익누계액(요약) 333
이익잉여금(요약) 333
*미처분이익잉여금 및 차기이월미처분이익잉여금(요약) 333
*당기순이익(요약) 333
부채와자본총계(요약) 333
매출액(요약) 333
매출원가(요약) 333
매출총이익(요약) 333
판매비와 관리비(요약) 333
급료 333
퇴직급여(요약) 333
복리후생비(요약) 333
세금과공과(요약) 333
임차료(요약) 333
감가상각비 333
연구비 333
기타 판매비와 관리비(요약) 333
영업이익(요약) 333
영업외수익(요약) 333
이자수익(요약) 333
배당금수익(요약) 333
외환차익(요약) 333
외화환산이익(요약) 333
지분법이익(요약) 333
기타영업외수익(요약) 333
영업외비용(요약) 333
이자비용(요약) 333
외환차손(요약) 333
외화환산손실(요약) 333
지분법손실(요약) 333
기타영업외비용(요약) 333
법인세비용차감전(계속사업)손익(요약) 333
(계속사업손익)법인세비용(요약) 333
계속사업이익(요약) 333
중단사업이익(요약) 333
*법인세효과(요약) 333
당기순이익(요약) 333
주당계속사업이익(요약) 333
주당순이익(요약) 333
희석화주당계속사업이익(요약) 333
희석화주당순이익(요약) 333
CPA수정후 당기순이익(요약) 333
*주당경상이익(2007년 이전 발생)(요약) 6968
*희석화주당경상이익(2007년 이전 발생)(요약) 6968
총자본증가율 1523
유형자산증가율 1523
유동자산증가율 1523
영업이익증가율 1523
경상이익증가율 (2007년 이전 발생) 9236
순이익증가율 1523
재고자산증가율 1523
자기자본증가율 1523
매출액증가율 1523
종업원1인당 부가가치증가율 1523
종업원수증가율 1523
비유동자산증가율 1523
종업원1인당 매출액증가율 1523
종업원1인당 인건비증가율 1523
매출액총이익률 1523
매출액영업이익률 1523
매출액경상이익률 (2007년 이전 발생) 9236
매출액순이익률 1523
총자본사업이익률 1523
총자본영업이익률 1523
총자본경상이익률 (2007년 이전 발생) 9236
총자본순이익률 1523
자기자본영업이익률 1523
자기자본경상이익률 (2007년 이전 발생) 9236
자기자본순이익률 1523
자본금영업이익률 1523
자본금경상이익률 (2007년 이전 발생) 9236
자본금순이익률 1523
조세 대 조세차감전순이익률 1523
기업경상이익률 (2007년 이전 발생) 9236
투자수익률 (2007년 이전 발생) 9236
기업순이익률 1523
경영자본영업이익률 1523
경영자본순이익률 1523
매출원가 대 매출액비율 1523
영업비율 1523
영업외손익률 1523
금융비용부담률 1523
외환이익 대 매출액비율 1523
광고선전비 대 매출액비율 1523
수지비율 1523
인건비 대 총비용비율 1523
조세공과 대 총비용비율 1523
금융비용 대 총비용비율 1523
감가상각비 대 총비용비율 1523
감가상각률 1523
누적감가상각률 1523
이자부담률 1523
지급이자율 1523
차입금평균이자율 1523
사내유보율 1523
사내유보 대 자기자본비율 1523
적립금비율(재정비율) 1523
평균배당률 1523
자기자본배당률 1523
배당성향 1523
1주당매출액 1523
EPS(Earning Per Share) 1523
1주당경상이익 (2007년 이전 발생) 9236
CPS(Cash flow Per Share) 1523
BPS(Book-value Per Share) 1523
유보율 1523
R & D 투자효율 1523
1주당영업이익 1523
유동자산구성비율 1523
재고자산 대 유동자산비율 1523
유동자산 대 비유동자산비율 1523
당좌자산구성비율 1523
비유동자산구성비율 1523
자기자본구성비율 1523
타인자본구성비율 1523
자기자본배율 1523
비유동비율 1523
비유동장기적합률 1523
유동비율 1523
당좌비율 1523
현금비율 1519
원재료비율 1523
매출채권비율 1523
재고자산 대 순운전자본비율 1523
매출채권 대 매입채무비율 1523
매출채권 대 상 1523
매입채무 대 재고자산비율 1523
부채비율 1523
유동부채비율 1523
단기차입금 대 총차입금비율 1523
비유동부채비율 1523
비유동부채 대 순운전자본비율 1523
순운전자본비율 1523
차입금의존도 1523
차입금비율 1523
이자보상배율(이자비용) 1523
이자보상배율(순금융비용) 1523
유보액대비율 1523
유보액 대 납입자본배율 1523
유동자산집중도 1523
비유동자산집중도 1523
투자집중도 1523
CASH FLOW 대 부채비율 1523
CASH FLOW 대 차입금비율 1523
CASH FLOW 대 총자본비율 1523
CASH FLOW 대 매출액비율 1523
영업이익대비이자보상배율 1523
총자본회전률 1523
경영자본회전률 1523
자기자본회전률 1523
자본금회전률 1523
타인자본회전률 1523
매입채무회전률 1523
매입채무회전기간 1523
유동자산회전률 1523
당좌자산회전률 1523
재고자산회전률 1523
재고자산회전기간 1523
상품 1523
원 1523
재공품회전률 1523
매출채권회전률 1523
매출채권회전기간 1523
비유동자산회전률 1523
유형자산회전율 1523
순운전자본회전률 1523
운전자본회전률 1523
1회전기간 1523
부가가치 1525
종업원1인당 부가가치 1525
종업원1인당 매출액 1525
종업원1인당 경상이익 (2007년 이전 발생) 9238
종업원1인당 순이익 1525
종업원1인당 인건비 1525
노동장비율 1525
기계장비율 1525
자본집약도 1525
총자본투자효율 1525
설비투자효율 1525
기계투자효율 1525
부가가치율 1525
노동소득분배율 1525
자본분배율 1525
이윤분배율 1525
부가가치.1 1525
법인세비용차감전(계속사업)손익 1525
인건비 1525
금융비용 1525
임차료 1525
조세공과 1525
감가상각비.1 1525
종업원1인당 부가가치.1 1525
총자본투자효율.1 1525
기계투자효율.1 1525
부가가치율.1 1525
종업원수 1525
PER(Price earnings ratio)(최고) 8870
PER(Price earnings ratio)(최저) 8870
PBR(Price book-value ratio)(최고) 8870
PBR(Price book-value ratio)(최저) 8870
PCR(Price cash-flow ratio)(최고) 8870
PCR(Price cash-flow ratio)(최저) 8870
PSR(Price sales ratio)(최고) 8870
PSR(Price sales ratio)(최저) 8870
기업가치(EV) 8875
EBITDA 8875
EBITDA/매출액 8875
EBITDA/금융비용 8875
EBITDA/평균발행주식수 8875
EV/EBITDA 9577

# **primary key 만들기**

In [5]:
# bankrupt df 의 primary key를 만들기 위한 작업
bankrupt['년'] = bankrupt['시간']
bankrupt = bankrupt.reset_index()

for i in range(len(bankrupt)):
    bankrupt['년'][i] = bankrupt['시간'][i][0:4]

bankrupt['key'] = bankrupt['종목코드'].astype(str) + bankrupt['년'].astype(str)

C:\Users\JH\AppData\Local\Temp/ipykernel_24172/352394691.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bankrupt['년'][i] = bankrupt['시간'][i][0:4]

In [6]:
# primary key CASE 1 : 거래소코드(55012) + [회계년도(2012) + 1](2013) ex) 550122013

train['년'] = (train['회계년도'].str[0:4].astype(int) + 1).astype(str)
train_full['년'] = (train_full['회계년도'].str[0:4].astype(int) + 1).astype(str)

# primary key CASE 2 : 거래소코드(55012) + [회계년도(2012)](2012) ex) 550122012

""" train['년'] = (train['회계년도'].str[0:4].astype(int)).astype(str)
train_full['년'] = (train_full['회계년도'].str[0:4].astype(int)).astype(str) """

train['key'] = train['거래소코드'].astype(str) + train['년'].astype(str)
train_full['key'] = train_full['거래소코드'].astype(str) + train_full['년'].astype(str)

# **부도 공시 기업 데이터 EDA**

In [7]:
# 상폐 사유가 발생한 기업 리스트
bankrupt['회사명'].unique()

array(['정산애강', '대호특수강', '에이치엘비', '대주산업', '세븐코스프', '엔케이바이오', 'ST&I',
       '지노시스템', '엠투엔', '아진산업', '파워넷', '유니크', '디에스피', '아이비진', 'IDH',
       '태산엘시디', '케이에스피', '나리지*온', '현대바이오', '미리넷', '미성포리테크', 'CT&T',
       '엘앤씨피', '동화기업', '블루젬디앤씨', '메디콕스', '에피밸리', '이룸지엔지', '오리엔트정공', '씨모텍',
       '콜마파마', '제이콤', '엠엔에프씨', '알티전자', '하이드로젠파워', '네오세미테크', '샤인시스템',
       '단성일렉트론', '쌈지', 'GK파워', '테이크시스템', '디보스', '케너텍', '포이보스', '에이스하이텍',
       '잘만테크', '영진코퍼레이션', '디지텍시스템', 'AJS', 'CU전자', '모린스', '엘컴텍', '한진피앤씨',
       '삼표시멘트', '오성첨단소재', '와이즈파워', '릭스솔루션', '에버테크노', '대성엘텍', '엠텍비젼',
       '피앤텔', '유니슨', '나노트로닉스', '디에스티', '에스비엠', '마이스코', '유일엔시스', '프리젠',
       '이디디컴퍼니', '아라온테크', '아큐텍', '아이팩토리', '위다스', '아이에이', '디브이에스',
       '오리엔탈정공', '삼우이엠씨', 'SSCP', '금강제강', '엔스퍼트', '동양텔레콤', '비앤비성원',
       '미주제강', '보광티에스', '평안물산', '에이프로테크놀로지', '얍엑스', '우경', '어울림 네트', '쎄니트',
       '씨앤케이인터', '에스에프씨', '이엠앤아이', '레이젠', '행남사', '엔에스브이', '신양오라컴', '코세스',
       '한국정밀기계', 'WI', '씨엔플러스', '우전', '테라사이언스', '썬코어', '나노스', '스틸플라워',
       '중앙디앤엠', '에스에스컴텍', '시너지이노베이션', '플렉스컴', '씨엘인터내셔널', '코데즈컴바인',
       '대한그린파워', '피엘에이', '에이디칩스', '동일철강', '아이앤씨', '디아이디', '티에스엠텍',
       '엘아이에스', '아이디에스', '우양에이치씨', 'GT&T', '한프', '크로바하이텍', '아리온', '에이치엔티',
       '럭슬', '참존글로벌', '매직마이크로', '비츠로시스', '아이엠텍', '휴온스블러썸', '이노와이즈',
       '바이오빌', '화진', 'EMW', '현진소재', '바른전자', '제낙스', 'CSA 코스믹', '솔고바이오',
       '이엠네트웍스', '이녹스', '알톤스포츠', '크루셜텍', '국순당', '리드', '스카이문스테크놀로지',
       '에스마크', '코썬바이오', '이엘케이', '에스디시스템', '에스앤더블류', '파나진', '유아이디'],
      dtype=object)

# **train&bankrupt 테이블 조인**

In [8]:
train_bankrupt_merge = pd.merge(train, bankrupt, on='key', how = 'outer')
train_bankrupt_merge

,회사명_x,거래소코드,회계년도,소속코드,상장폐지일,년_x,key,index,번호,시간,회사명_y,종목코드,공시제목,제출인,년_y
0,(주)CMG제약,58820.0,2000/12,5.0,NaN,2001,588202001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,(주)CMG제약,58820.0,2001/12,5.0,NaN,2002,588202002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,(주)CMG제약,58820.0,2002/12,5.0,NaN,2003,588202003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,(주)CMG제약,58820.0,2003/12,5.0,NaN,2004,588202004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,(주)CMG제약,58820.0,2004/12,5.0,NaN,2005,588202005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27374,NaN,NaN,NaN,NaN,NaN,NaN,1019702015,89.0,12.0,2015-03-02 18:15,우양에이치씨,101970.0,회생절차개시신청,우양에이치씨,2015
27375,NaN,NaN,NaN,NaN,NaN,NaN,336002020,6.0,244.0,2020-11-17 16:01,럭슬,33600.0,[정정]회생절차개시신청,럭슬,2020
27376,NaN,NaN,NaN,NaN,NaN,NaN,336002020,20.0,230.0,2020-09-02 15:40,럭슬,33600.0,회생절차개시신청[정],럭슬,2020
27377,NaN,NaN,NaN,NaN,NaN,NaN,862502020,29.0,221.0,2020-07-28 14:54,이노와이즈,86250.0,회생절차개시결정,화신테크,2020
27378,NaN,NaN,NaN,NaN,NaN,NaN,862502020,44.0,206.0,2020-05-08 15:03,이노와이즈,86250.0,회생절차개시신청,화신테크,2020

In [20]:
train_full_bankrupt_merge = pd.merge(train_full, bankrupt[['key','공시제목']], on='key', how = 'outer')
train_full_bankrupt_merge.head()

,회사명,거래소코드,회계년도,소속코드,상장폐지일,감사의견코드,자산총계(요약),유동자산(요약),당좌자산(요약),현금 및 현금성자산(요약),...,PSR(Price sales ratio)(최저),기업가치(EV),EBITDA,EBITDA/매출액,EBITDA/금융비용,EBITDA/평균발행주식수,EV/EBITDA,년,key,공시제목
0,(주)CMG제약,58820.0,2000/12,5.0,NaN,UQ,28990.0,21169.0,10541.0,4330.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2001,588202001,NaN
1,(주)CMG제약,58820.0,2001/12,5.0,NaN,UQ,20908.0,16359.0,2307.0,1829.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2002,588202002,NaN
2,(주)CMG제약,58820.0,2002/12,5.0,NaN,UQ,15401.0,9880.0,1436.0,355.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2003,588202003,NaN
3,(주)CMG제약,58820.0,2003/12,5.0,NaN,UQ,11063.0,8534.0,1083.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004,588202004,NaN
4,(주)CMG제약,58820.0,2004/12,5.0,NaN,UQ,5179.0,3893.0,445.0,11.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2005,588202005,NaN

In [10]:
print(train_full.shape, bankrupt.shape, train_full_bankrupt_merge.shape)
# merge시 outer에 해당하는 부분
train_full.shape[0] + bankrupt.shape[0] - train_full_bankrupt_merge.shape[0]

(27166, 269) (394, 9) (27379, 270)

181

In [11]:
print(train.shape, bankrupt.shape, train_bankrupt_merge.shape)
# merge시 outer에 해당하는 부분
train.shape[0] + bankrupt.shape[0] - train_bankrupt_merge.shape[0]

(27166, 7) (394, 9) (27379, 15)

181

# **테이블 저장**

In [288]:
train_full_bankrupt_merge.to_csv(r'C:\Users\JH\Desktop\Final\CBA\Data\데이터정리중\재무변수_부도이유.csv')

# **train과 inner로 merge되지 않은 기업**

In [12]:
subset = train_bankrupt_merge.fillna('임시')
subset

,회사명_x,거래소코드,회계년도,소속코드,상장폐지일,년_x,key,index,번호,시간,회사명_y,종목코드,공시제목,제출인,년_y
0,(주)CMG제약,58820.0,2000/12,5.0,임시,2001,588202001,임시,임시,임시,임시,임시,임시,임시,임시
1,(주)CMG제약,58820.0,2001/12,5.0,임시,2002,588202002,임시,임시,임시,임시,임시,임시,임시,임시
2,(주)CMG제약,58820.0,2002/12,5.0,임시,2003,588202003,임시,임시,임시,임시,임시,임시,임시,임시
3,(주)CMG제약,58820.0,2003/12,5.0,임시,2004,588202004,임시,임시,임시,임시,임시,임시,임시,임시
4,(주)CMG제약,58820.0,2004/12,5.0,임시,2005,588202005,임시,임시,임시,임시,임시,임시,임시,임시
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27374,임시,임시,임시,임시,임시,임시,1019702015,89.0,12.0,2015-03-02 18:15,우양에이치씨,101970.0,회생절차개시신청,우양에이치씨,2015
27375,임시,임시,임시,임시,임시,임시,336002020,6.0,244.0,2020-11-17 16:01,럭슬,33600.0,[정정]회생절차개시신청,럭슬,2020
27376,임시,임시,임시,임시,임시,임시,336002020,20.0,230.0,2020-09-02 15:40,럭슬,33600.0,회생절차개시신청[정],럭슬,2020
27377,임시,임시,임시,임시,임시,임시,862502020,29.0,221.0,2020-07-28 14:54,이노와이즈,86250.0,회생절차개시결정,화신테크,2020
27378,임시,임시,임시,임시,임시,임시,862502020,44.0,206.0,2020-05-08 15:03,이노와이즈,86250.0,회생절차개시신청,화신테크,2020

In [13]:
condi = subset.loc[subset['회사명_x'] == '임시', '종목코드'].unique()
condi

array([31800.0, 33850.0, 33310.0, 13310.0, 28300.0, 19260.0, 54020.0,
       80140.0, 37240.0, 45470.0, 101970.0, 33600.0, 86250.0],
      dtype=object)

In [14]:
subset.loc[subset['key'] == '338502001', '공시제목'] = '화의채무변제완료보고서제출'
subset.loc[subset['key'] == '338502001']

,회사명_x,거래소코드,회계년도,소속코드,상장폐지일,년_x,key,index,번호,시간,회사명_y,종목코드,공시제목,제출인,년_y
14214,(주)지노시스템,33850.0,2000/12,4.0,2011/05/07,2001,338502001,임시,임시,임시,임시,임시,화의채무변제완료보고서제출,임시,임시

In [15]:
subset.head()

,회사명_x,거래소코드,회계년도,소속코드,상장폐지일,년_x,key,index,번호,시간,회사명_y,종목코드,공시제목,제출인,년_y
0,(주)CMG제약,58820.0,2000/12,5.0,임시,2001,588202001,임시,임시,임시,임시,임시,임시,임시,임시
1,(주)CMG제약,58820.0,2001/12,5.0,임시,2002,588202002,임시,임시,임시,임시,임시,임시,임시,임시
2,(주)CMG제약,58820.0,2002/12,5.0,임시,2003,588202003,임시,임시,임시,임시,임시,임시,임시,임시
3,(주)CMG제약,58820.0,2003/12,5.0,임시,2004,588202004,임시,임시,임시,임시,임시,임시,임시,임시
4,(주)CMG제약,58820.0,2004/12,5.0,임시,2005,588202005,임시,임시,임시,임시,임시,임시,임시,임시

In [16]:
for i in range(len(subset.loc[subset['회사명_x'] == '임시', '종목코드'].unique())):
    print(subset.loc[subset['종목코드'] == subset.loc[subset['회사명_x'] == '임시', '종목코드'].unique()[i]]['공시제목'].values)

['회사정리절차종결결정' '회사정리절차종결신청' '회사정리절차개시결정(씨티아이반도체(주) (1))'
 '회사정리절차개시결정(씨티아이반도체(주) (2))']
['화의채무변제완료보고서제출']
['화의채무변제완료보고서제출' '은행거래재개((주)우진산전)']
['회사정리절차개시결정(아진산업(주))']
['회사정리절차종결결정' '회사정리절차종결신청' '은행거래재개(국제정공(주))' '회사정리절차개시결정(국제정공(주) (1))'
 '회사정리절차개시결정(국제정공(주) (2))']
['화의채무변제완료보고서제출' '은행거래재개((주)한올)']
['부도발생']
['[정정]회생절차개시결정' '[정정]회생절차개시결정[정]' '[정정]회생절차개시결정[정]' '회생절차개시결정[정]'
 '회생절차개시신청' '회생절차 폐지결정']
['내부결산시점 관리종목 지정 또는 상장폐지 사유 발생']
['내부결산시점 관리종목 지정 또는 상장폐지 사유 발생']
['부도발생' '회생절차개시신청']
['[정정]회생절차개시신청' '회생절차개시신청[정]']
['회생절차개시결정' '회생절차개시신청']

In [17]:
print('inner 되지 않은 기업 리스트 :',subset.loc[subset['회사명_x'] == '임시', '회사명_y'].unique())
print('-'*130)
print('inner 되지 않은 기업 종목코드 :',subset.loc[subset['회사명_x'] == '임시', '종목코드'].unique())
print('-'*130)
print('inner 되지 않은 기업 수 :',len(subset.loc[subset['회사명_x'] == '임시', '회사명_y'].unique()))

inner 되지 않은 기업 리스트 : ['ST&I' '지노시스템' '엠투엔' '아진산업' '에이치엘비' '엔케이바이오' 'GK파워' '디보스' '평안물산'
 '에이프로테크놀로지' '우양에이치씨' '럭슬' '이노와이즈']
----------------------------------------------------------------------------------------------------------------------------------
inner 되지 않은 기업 종목코드 : [31800.0 33850.0 33310.0 13310.0 28300.0 19260.0 54020.0 80140.0 37240.0
 45470.0 101970.0 33600.0 86250.0]
----------------------------------------------------------------------------------------------------------------------------------
inner 되지 않은 기업 수 : 13

In [18]:
for i in range(len(subset.loc[subset['회사명_x'] == '임시', '회사명_y'].unique())):
    print('기업명 :', subset.loc[subset['회사명_x'] == '임시', '회사명_y'].unique()[i], '종목코드 :', subset.loc[subset['회사명_x'] == '임시', '종목코드'].unique()[i])

기업명 : ST&I 종목코드 : 31800.0
기업명 : 지노시스템 종목코드 : 33850.0
기업명 : 엠투엔 종목코드 : 33310.0
기업명 : 아진산업 종목코드 : 13310.0
기업명 : 에이치엘비 종목코드 : 28300.0
기업명 : 엔케이바이오 종목코드 : 19260.0
기업명 : GK파워 종목코드 : 54020.0
기업명 : 디보스 종목코드 : 80140.0
기업명 : 평안물산 종목코드 : 37240.0
기업명 : 에이프로테크놀로지 종목코드 : 45470.0
기업명 : 우양에이치씨 종목코드 : 101970.0
기업명 : 럭슬 종목코드 : 33600.0
기업명 : 이노와이즈 종목코드 : 86250.0