In [3]:
import pandas as pd

In [12]:
df1 = pd.read_csv(r'C:\Users\JH\Desktop\Final\Ubion-CorporateBankruptcyAnalysis\Code\JH\code\modeling\4년차검증.csv')

In [13]:
df1[['model', 'SET1 val Accuracy', 'SET1 test Accuracy']].sort_values(by='SET1 test Accuracy', ascending=False)

           model  SET1 val Accuracy  SET1 test Accuracy
7       Catboost           0.678010              0.7579
2       Adaboost           0.653141              0.7474
5            SVC           0.670157              0.7359
6       lightGBM           0.666230              0.7320
4            KNN           0.624346              0.7279
8            MLP           0.619110              0.7279
1  Random Forest           0.660995              0.7268
3       logistic           0.662304              0.7234
9        Xgboost           0.659686              0.7085
0  Decision Tree           0.587696              0.6490

In [14]:
df1[['model', 'SET2 val Accuracy', 'SET2 test Accuracy']].sort_values(by='SET2 test Accuracy', ascending=False)

           model  SET2 val Accuracy  SET2 test Accuracy
2       Adaboost           0.657068              0.7661
7       Catboost           0.698953              0.7653
1  Random Forest           0.684555              0.7400
6       lightGBM           0.664921              0.7387
5            SVC           0.659686              0.7335
4            KNN           0.607330              0.7288
9        Xgboost           0.674084              0.7271
3       logistic           0.657068              0.7231
0  Decision Tree           0.583770              0.6503
8            MLP           0.595550              0.6455

In [15]:
df1[['model','SET1 test Accuracy','SET1 test f1-Score', 'SET1 test Precision', 'SET1 test Recall']].sort_values(by='SET1 test f1-Score', ascending=False)

,model,SET1 test Accuracy,SET1 test f1-Score,SET1 test Precision,SET1 test Recall
1,Random Forest,0.7268,0.0129,0.0065,0.6667
7,Catboost,0.7579,0.0127,0.0064,0.5833
6,lightGBM,0.7320,0.0123,0.0062,0.6250
3,logistic,0.7234,0.0119,0.0060,0.6250
2,Adaboost,0.7474,0.0113,0.0057,0.5417
8,MLP,0.7279,0.0113,0.0057,0.5833
5,SVC,0.7359,0.0108,0.0055,0.5417
9,Xgboost,0.7085,0.0106,0.0053,0.5833
4,KNN,0.7279,0.0089,0.0045,0.4583
0,Decision Tree,0.6490,0.0076,0.0038,0.5000

In [16]:
df1[['model', 'SET2 test Accuracy','SET2 test f1_Score', 'SET2 test Precision', 'SET2 test Recall']].sort_values(by='SET2 test f1_Score', ascending=False)

,model,SET2 test Accuracy,SET2 test f1_Score,SET2 test Precision,SET2 test Recall
7,Catboost,0.7653,0.0140,0.0071,0.6250
1,Random Forest,0.7400,0.0135,0.0068,0.6667
9,Xgboost,0.7271,0.0129,0.0065,0.6667
6,lightGBM,0.7387,0.0126,0.0064,0.6250
3,logistic,0.7231,0.0119,0.0060,0.6250
2,Adaboost,0.7661,0.0113,0.0057,0.5000
5,SVC,0.7335,0.0107,0.0054,0.5417
8,MLP,0.6455,0.0093,0.0047,0.6250
4,KNN,0.7288,0.0090,0.0045,0.4583
0,Decision Tree,0.6503,0.0076,0.0038,0.5000