In [3]:
import pandas as pd

In [17]:
df1 = pd.read_csv(r'C:\Users\JH\Desktop\Final\Ubion-CorporateBankruptcyAnalysis\Code\JH\code\modeling\0년차검증.csv')

In [18]:
df1[['model', 'SET1 val Accuracy', 'SET1 test Accuracy']].sort_values(by='SET1 test Accuracy', ascending=False)

           model  SET1 val Accuracy  SET1 test Accuracy
4            KNN           0.821839              0.8997
3       logistic           0.834770              0.8972
7       Catboost           0.843391              0.8674
6       lightGBM           0.836207              0.8576
5            SVC           0.811782              0.8529
9        Xgboost           0.823276              0.8514
2       Adaboost           0.844828              0.8495
1  Random Forest           0.847701              0.8442
8            MLP           0.814655              0.7918
0  Decision Tree           0.764368              0.7801

In [19]:
df1[['model', 'SET2 val Accuracy', 'SET2 test Accuracy']].sort_values(by='SET2 test Accuracy', ascending=False)

           model  SET2 val Accuracy  SET2 test Accuracy
8            MLP           0.806034              0.9550
3       logistic           0.856322              0.9087
4            KNN           0.807471              0.8996
7       Catboost           0.883621              0.8713
9        Xgboost           0.866379              0.8645
5            SVC           0.816092              0.8534
1  Random Forest           0.889368              0.8533
6       lightGBM           0.869253              0.8526
2       Adaboost           0.864943              0.8494
0  Decision Tree           0.801724              0.7819

In [20]:
df1[['model','SET1 test Accuracy','SET1 test f1-Score', 'SET1 test Precision', 'SET1 test Recall']].sort_values(by='SET1 test f1-Score', ascending=False)

,model,SET1 test Accuracy,SET1 test f1-Score,SET1 test Precision,SET1 test Recall
3,logistic,0.8972,0.0821,0.0435,0.7241
4,KNN,0.8997,0.0803,0.0426,0.6897
7,Catboost,0.8674,0.0735,0.0384,0.8276
6,lightGBM,0.8576,0.0714,0.0372,0.8621
9,Xgboost,0.8514,0.0674,0.0351,0.8448
1,Random Forest,0.8442,0.0632,0.0329,0.8276
2,Adaboost,0.8495,0.0602,0.0313,0.7586
5,SVC,0.8529,0.0575,0.0300,0.7069
8,MLP,0.7918,0.0480,0.0247,0.8276
0,Decision Tree,0.7801,0.0429,0.0220,0.7759

In [21]:
df1[['model', 'SET2 test Accuracy','SET2 test f1_Score', 'SET2 test Precision', 'SET2 test Recall']].sort_values(by='SET2 test f1_Score', ascending=False)

,model,SET2 test Accuracy,SET2 test f1_Score,SET2 test Precision,SET2 test Recall
8,MLP,0.9550,0.1526,0.0867,0.6379
3,logistic,0.9087,0.0974,0.0520,0.7759
4,KNN,0.8996,0.0821,0.0436,0.7069
7,Catboost,0.8713,0.0798,0.0418,0.8793
9,Xgboost,0.8645,0.0734,0.0383,0.8448
1,Random Forest,0.8533,0.0733,0.0382,0.9138
6,lightGBM,0.8526,0.0692,0.0360,0.8621
2,Adaboost,0.8494,0.0652,0.0339,0.8276
5,SVC,0.8534,0.0577,0.0301,0.7069
0,Decision Tree,0.7819,0.0451,0.0232,0.8103