In [30]:
import pandas as pd

train = pd.read_csv(r'C:\Users\qorwl\Desktop\Ubion-CorporateBankruptcyAnalysis\Data\데이터정리중\재무변수_부도이유.csv', index_col='Unnamed: 0')

In [31]:
train

,회사명,거래소코드,회계년도,소속코드,상장폐지일,감사의견코드,자산총계(요약),유동자산(요약),당좌자산(요약),현금 및 현금성자산(요약),...,PSR(Price sales ratio)(최저),기업가치(EV),EBITDA,EBITDA/매출액,EBITDA/금융비용,EBITDA/평균발행주식수,EV/EBITDA,년,key,공시제목
0,(주)CMG제약,58820.0,2000/12,5.0,NaN,UQ,28990.0,21169.0,10541.0,4330.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2001.0,588202001,NaN
1,(주)CMG제약,58820.0,2001/12,5.0,NaN,UQ,20908.0,16359.0,2307.0,1829.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2002.0,588202002,NaN
2,(주)CMG제약,58820.0,2002/12,5.0,NaN,UQ,15401.0,9880.0,1436.0,355.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2003.0,588202003,NaN
3,(주)CMG제약,58820.0,2003/12,5.0,NaN,UQ,11063.0,8534.0,1083.0,2.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2004.0,588202004,NaN
4,(주)CMG제약,58820.0,2004/12,5.0,NaN,UQ,5179.0,3893.0,445.0,11.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2005.0,588202005,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27374,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1019702015,회생절차개시신청
27375,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,336002020,[정정]회생절차개시신청
27376,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,336002020,회생절차개시신청[정]
27377,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,862502020,회생절차개시결정
27378,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,862502020,회생절차개시신청

### 회사명 NaN 제거

In [32]:
train.dropna(subset=['회사명'], axis = 0, inplace=True)

### 부도컬럼 생성

In [34]:
train['부도'] = ""

감사의견거절 감사보고서 부적정, 의견거절, 범위제한한정
- 의견코드 : AG, DS, DI, DU, QS

In [36]:
train[['소속코드','감사의견코드','공시제목']]

       소속코드 감사의견코드 공시제목
0       5.0     UQ  NaN
1       5.0     UQ  NaN
2       5.0     UQ  NaN
3       5.0     UQ  NaN
4       5.0     UQ  NaN
...     ...    ...  ...
27352   5.0     UQ  NaN
27353   5.0     UQ  NaN
27354   5.0     UQ  NaN
27355   5.0     UQ  NaN
27356   5.0     UQ  NaN

[27357 rows x 3 columns]

In [55]:
con1 = train['소속코드'] == '4.0'
con2 = train['감사의견코드'] == 'DS'
con3 = train['공시제목'] != 'NaN'


train['부도'] = train.apply[con1 | con2 | con3] = 1
train['부도']

TypeError: unsupported operand type(s) for &: 'str' and 'str'

In [16]:
train.isnull().sum()[1]

22

In [18]:
for i in range(270):
    print(train.columns[i], train.isnull().sum()[i])

회사명 22
거래소코드 22
회계년도 22
소속코드 22
상장폐지일 21943
감사의견코드 535
자산총계(요약) 355
유동자산(요약) 355
당좌자산(요약) 355
현금 및 현금성자산(요약) 355
단기투자자산(요약) 355
단기예금(요약) 355
단기매매증권(요약) 355
단기대여금(요약) 355
기타단기투자자산(요약) 355
매출채권(요약) 355
*할인어음 또는 배서어음(요약) 355
기타당좌자산(요약) 355
재고자산(요약) 355
상품(요약) 355
제품(요약) 355
반제품(요약) 355
재공품(요약) 355
원재료(요약) 355
기타재고자산(요약) 355
임대주택자산(요약) 355
비유동자산(요약) 355
투자자산(요약) 355
*장기금융상품(요약) 355
*투자유가증권(장기투자증권)(요약) 355
유형자산(요약) 355
토지 355
건설중인자산 355
건물 355
기계장치 355
차량운반구 355
렌탈자산 355
설비자산 355
무형자산(요약) 355
기타비유동자산(요약) 355
이연자산(요약) 355
부채총계(요약) 355
유동부채(요약) 355
매입채무(요약) 355
단기차입금(요약) 355
유동성장기부채(요약) 355
기타유동부채(요약) 355
비유동부채(요약) 355
사채(요약) 355
장기차입금(요약) 355
제충당금(요약) 355
기타비유동부채(요약) 355
이연부채(요약) 355
자본총계(요약) 355
자본금(요약) 355
자본잉여금(요약) 355
자본조정(요약) 355
기타포괄손익누계액(요약) 355
이익잉여금(요약) 355
*미처분이익잉여금 및 차기이월미처분이익잉여금(요약) 355
*당기순이익(요약) 355
부채와자본총계(요약) 355
매출액(요약) 355
매출원가(요약) 355
매출총이익(요약) 355
판매비와 관리비(요약) 355
급료 355
퇴직급여(요약) 355
복리후생비(요약) 355
세금과공과(요약) 355
임차료(요약) 355
감가상각비 355
연구비 355
기타 판매비와 관리비(요약) 355
영업이익(요약) 355
영업외수익(요약) 355
이자수익(요약) 355
배당금수익(요약) 355
외환차익(요약) 355
외화환산이익(요약) 355
지분법이익(요약) 355
기타영업외수익(요약) 355
영업외비용(요약) 355
이자비용(요약) 355
외환차손(요약) 355
외화환산손실(요약) 355
지분법손실(요약) 355
기타영업외비용(요약) 355
법인세비용차감전(계속사업)손익(요약) 355
(계속사업손익)법인세비용(요약) 355
계속사업이익(요약) 355
중단사업이익(요약) 355
*법인세효과(요약) 355
당기순이익(요약) 355
주당계속사업이익(요약) 355
주당순이익(요약) 355
희석화주당계속사업이익(요약) 355
희석화주당순이익(요약) 355
CPA수정후 당기순이익(요약) 355
*주당경상이익(2007년 이전 발생)(요약) 7055
*희석화주당경상이익(2007년 이전 발생)(요약) 7055
총자본증가율 1545
유형자산증가율 1545
유동자산증가율 1545
영업이익증가율 1545
경상이익증가율 (2007년 이전 발생) 9323
순이익증가율 1545
재고자산증가율 1545
자기자본증가율 1545
매출액증가율 1545
종업원1인당 부가가치증가율 1545
종업원수증가율 1545
비유동자산증가율 1545
종업원1인당 매출액증가율 1545
종업원1인당 인건비증가율 1545
매출액총이익률 1545
매출액영업이익률 1545
매출액경상이익률 (2007년 이전 발생) 9323
매출액순이익률 1545
총자본사업이익률 1545
총자본영업이익률 1545
총자본경상이익률 (2007년 이전 발생) 9323
총자본순이익률 1545
자기자본영업이익률 1545
자기자본경상이익률 (2007년 이전 발생) 9323
자기자본순이익률 1545
자본금영업이익률 1545
자본금경상이익률 (2007년 이전 발생) 9323
자본금순이익률 1545
조세 대 조세차감전순이익률 1545
기업경상이익률 (2007년 이전 발생) 9323
투자수익률 (2007년 이전 발생) 9323
기업순이익률 1545
경영자본영업이익률 1545
경영자본순이익률 1545
매출원가 대 매출액비율 1545
영업비율 1545
영업외손익률 1545
금융비용부담률 1545
외환이익 대 매출액비율 1545
광고선전비 대 매출액비율 1545
수지비율 1545
인건비 대 총비용비율 1545
조세공과 대 총비용비율 1545
금융비용 대 총비용비율 1545
감가상각비 대 총비용비율 1545
감가상각률 1545
누적감가상각률 1545
이자부담률 1545
지급이자율 1545
차입금평균이자율 1545
사내유보율 1545
사내유보 대 자기자본비율 1545
적립금비율(재정비율) 1545
평균배당률 1545
자기자본배당률 1545
배당성향 1545
1주당매출액 1545
EPS(Earning Per Share) 1545
1주당경상이익 (2007년 이전 발생) 9323
CPS(Cash flow Per Share) 1545
BPS(Book-value Per Share) 1545
유보율 1545
R & D 투자효율 1545
1주당영업이익 1545
유동자산구성비율 1545
재고자산 대 유동자산비율 1545
유동자산 대 비유동자산비율 1545
당좌자산구성비율 1545
비유동자산구성비율 1545
자기자본구성비율 1545
타인자본구성비율 1545
자기자본배율 1545
비유동비율 1545
비유동장기적합률 1545
유동비율 1545
당좌비율 1545
현금비율 1541
원재료비율 1545
매출채권비율 1545
재고자산 대 순운전자본비율 1545
매출채권 대 매입채무비율 1545
매출채권 대 상 1545
매입채무 대 재고자산비율 1545
부채비율 1545
유동부채비율 1545
단기차입금 대 총차입금비율 1545
비유동부채비율 1545
비유동부채 대 순운전자본비율 1545
순운전자본비율 1545
차입금의존도 1545
차입금비율 1545
이자보상배율(이자비용) 1545
이자보상배율(순금융비용) 1545
유보액대비율 1545
유보액 대 납입자본배율 1545
유동자산집중도 1545
비유동자산집중도 1545
투자집중도 1545
CASH FLOW 대 부채비율 1545
CASH FLOW 대 차입금비율 1545
CASH FLOW 대 총자본비율 1545
CASH FLOW 대 매출액비율 1545
영업이익대비이자보상배율 1545
총자본회전률 1545
경영자본회전률 1545
자기자본회전률 1545
자본금회전률 1545
타인자본회전률 1545
매입채무회전률 1545
매입채무회전기간 1545
유동자산회전률 1545
당좌자산회전률 1545
재고자산회전률 1545
재고자산회전기간 1545
상품 1545
원 1545
재공품회전률 1545
매출채권회전률 1545
매출채권회전기간 1545
비유동자산회전률 1545
유형자산회전율 1545
순운전자본회전률 1545
운전자본회전률 1545
1회전기간 1545
부가가치 1547
종업원1인당 부가가치 1547
종업원1인당 매출액 1547
종업원1인당 경상이익 (2007년 이전 발생) 9325
종업원1인당 순이익 1547
종업원1인당 인건비 1547
노동장비율 1547
기계장비율 1547
자본집약도 1547
총자본투자효율 1547
설비투자효율 1547
기계투자효율 1547
부가가치율 1547
노동소득분배율 1547
자본분배율 1547
이윤분배율 1547
부가가치.1 1547
법인세비용차감전(계속사업)손익 1547
인건비 1547
금융비용 1547
임차료 1547
조세공과 1547
감가상각비.1 1547
종업원1인당 부가가치.1 1547
총자본투자효율.1 1547
기계투자효율.1 1547
부가가치율.1 1547
종업원수 1547
PER(Price earnings ratio)(최고) 8902
PER(Price earnings ratio)(최저) 8902
PBR(Price book-value ratio)(최고) 8902
PBR(Price book-value ratio)(최저) 8902
PCR(Price cash-flow ratio)(최고) 8902
PCR(Price cash-flow ratio)(최저) 8902
PSR(Price sales ratio)(최고) 8902
PSR(Price sales ratio)(최저) 8902
기업가치(EV) 8907
EBITDA 8907
EBITDA/매출액 8907
EBITDA/금융비용 8907
EBITDA/평균발행주식수 8907
EV/EBITDA 9624
년 22
key 0
공시제목 26985

In [21]:
train[['매출액영업이익률', '매출액경상이익률 (2007년 이전 발생)']].transpose()

,0,1,2,3,4,5,6,7,8,9,...,27369,27370,27371,27372,27373,27374,27375,27376,27377,27378
매출액영업이익률,NaN,1.86,-14.46,-5.26,-21.69,-47.66,-35.59,-74.3,-35.02,-85.24,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
매출액경상이익률 (2007년 이전 발생),NaN,0.71,NaN,0.89,-23.99,-61.11,-102.58,NaN,0.00,0.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN